name: 'Review reminder'
description: 'Send reminders to authors, reviewers... of a pull request'
author: 'Baptiste Lombard'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  reminder-comment:
    description: 'Message to the requested reviewers'
    default: "Don't forget to review this PR !" # Note that "Hey @reviewer1, @reviewer2, @... !" will be appended before.
    required: false
  days-before-reminder:
    description: 'The number of days before the requested reviewers will receive a reminder'
    default: '1'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
