name: 'Review reminder'
description: 'Send reminders to requested reviewers of a pull request'
author: 'Baptiste Lombard'
branding:
  icon: 'bell'
  color: 'yellow'
inputs:
  token:
    description: 'Your GITHUB_TOKEN secret'
    required: true
  reminder-comment:
    description: 'Message to the requested reviewers'
    default: "Don't forget to review this PR !" # Note that "Hey @reviewer1, @reviewer2, @... !" will be appended before.
    required: false
  reminder-label:
    description: 'Label to add to the PR when a reminder is sent'
    required: false
  required-label:
    description: 'Label that is required to already exist to send this reminder'
    required: false
  days-before-reminder:
    description: 'The number of days before the requested reviewers will receive a reminder'
    default: '1'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
