name: CI

on: [push]

jobs:
  test:
    name: Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tests
      run: ./
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
