name: CI

on: [push]

jobs:
  test:
    name: Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tests
      run: |
        npm ci
        npm t
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
